[project]
name = "webview-takeout"
version = "0.1.0"
description = "webview-takeout project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.24.0",
    "mcp[cli]>=1.7.1",
]

[tool.ruff]
line-length = 88
target-version = "py313" 